window.ALL_WORLD_CUP_TEAMS = [
  { name: 'Argentina', confed: 'CONMEBOL', tier: 'Elite', group: 'C', hostCities: ['Los Angeles', 'Houston', 'Miami'] },
  { name: 'Australia', confed: 'AFC', tier: 'Strong', group: 'D', hostCities: ['Seattle', 'San Francisco', 'Vancouver'] },
  { name: 'Austria', confed: 'UEFA', tier: 'Strong', group: 'E', hostCities: ['Kansas City', 'Dallas', 'Atlanta'] },
  { name: 'Belgium', confed: 'UEFA', tier: 'Elite', group: 'F', hostCities: ['New York', 'Boston', 'Philadelphia'] },
  { name: 'Bosnia and Herzegovina', confed: 'UEFA', tier: 'Contender', group: 'G', hostCities: ['Chicago', 'Houston', 'Dallas'] },
  { name: 'Brazil', confed: 'CONMEBOL', tier: 'Elite', group: 'H', hostCities: ['Los Angeles', 'Miami', 'Dallas'] },
  { name: 'Canada', confed: 'CONCACAF', tier: 'Contender', group: 'A', hostCities: ['Toronto', 'Vancouver', 'Montreal'] },
  { name: 'Cape Verde', confed: 'CAF', tier: 'Contender', group: 'B', hostCities: ['Houston', 'Atlanta', 'Boston'] },
  { name: 'Colombia', confed: 'CONMEBOL', tier: 'Elite', group: 'C', hostCities: ['Miami', 'Houston', 'Los Angeles'] },
  { name: 'Croatia', confed: 'UEFA', tier: 'Elite', group: 'D', hostCities: ['New York', 'Dallas', 'Atlanta'] },
  { name: 'Curaçao', confed: 'CONCACAF', tier: 'Contender', group: 'E', hostCities: ['Miami', 'Houston', 'Mexico City'] },
  { name: 'Czech Republic', confed: 'UEFA', tier: 'Contender', group: 'F', hostCities: ['Philadelphia', 'Boston', 'Kansas City'] },
  { name: 'DR Congo', confed: 'CAF', tier: 'Contender', group: 'G', hostCities: ['Atlanta', 'Houston', 'Seattle'] },
  { name: 'Ecuador', confed: 'CONMEBOL', tier: 'Strong', group: 'H', hostCities: ['Los Angeles', 'Kansas City', 'Seattle'] },
  { name: 'Egypt', confed: 'CAF', tier: 'Strong', group: 'A', hostCities: ['Miami', 'Dallas', 'New York'] },
  { name: 'England', confed: 'UEFA', tier: 'Elite', group: 'B', hostCities: ['Boston', 'New York', 'Philadelphia'] },
  { name: 'France', confed: 'UEFA', tier: 'Elite', group: 'C', hostCities: ['Los Angeles', 'Miami', 'Chicago'] },
  { name: 'Germany', confed: 'UEFA', tier: 'Elite', group: 'D', hostCities: ['Atlanta', 'Dallas', 'New York'] },
  { name: 'Ghana', confed: 'CAF', tier: 'Strong', group: 'E', hostCities: ['Philadelphia', 'Houston', 'Kansas City'] },
  { name: 'Haiti', confed: 'CONCACAF', tier: 'Contender', group: 'F', hostCities: ['Miami', 'Orlando', 'New York'] },
  { name: 'Iran', confed: 'AFC', tier: 'Strong', group: 'G', hostCities: ['Dallas', 'Houston', 'San Francisco'] },
  { name: 'Iraq', confed: 'AFC', tier: 'Contender', group: 'H', hostCities: ['Kansas City', 'Atlanta', 'Seattle'] },
  { name: 'Ivory Coast', confed: 'CAF', tier: 'Strong', group: 'A', hostCities: ['Houston', 'Miami', 'Boston'] },
  { name: 'Jordan', confed: 'AFC', tier: 'Contender', group: 'B', hostCities: ['Los Angeles', 'Dallas', 'Seattle'] },
  { name: 'Japan', confed: 'AFC', tier: 'Elite', group: 'C', hostCities: ['Los Angeles', 'San Francisco', 'Seattle'] },
  { name: 'Mexico', confed: 'CONCACAF', tier: 'Elite', group: 'D', hostCities: ['Mexico City', 'Guadalajara', 'Monterrey'] },
  { name: 'Morocco', confed: 'CAF', tier: 'Elite', group: 'E', hostCities: ['New York', 'Boston', 'Philadelphia'] },
  { name: 'Netherlands', confed: 'UEFA', tier: 'Elite', group: 'F', hostCities: ['Atlanta', 'Miami', 'Dallas'] },
  { name: 'New Zealand', confed: 'OFC', tier: 'Contender', group: 'G', hostCities: ['Seattle', 'Vancouver', 'San Francisco'] },
  { name: 'Norway', confed: 'UEFA', tier: 'Strong', group: 'H', hostCities: ['New York', 'Chicago', 'Boston'] },
  { name: 'Panama', confed: 'CONCACAF', tier: 'Contender', group: 'A', hostCities: ['Miami', 'Houston', 'Los Angeles'] },
  { name: 'Paraguay', confed: 'CONMEBOL', tier: 'Strong', group: 'B', hostCities: ['Kansas City', 'Dallas', 'Atlanta'] },
  { name: 'Portugal', confed: 'UEFA', tier: 'Elite', group: 'C', hostCities: ['Boston', 'New York', 'Miami'] },
  { name: 'Qatar', confed: 'AFC', tier: 'Contender', group: 'D', hostCities: ['Houston', 'Dallas', 'Los Angeles'] },
  { name: 'Saudi Arabia', confed: 'AFC', tier: 'Strong', group: 'E', hostCities: ['Miami', 'New York', 'Dallas'] },
  { name: 'Scotland', confed: 'UEFA', tier: 'Contender', group: 'F', hostCities: ['Chicago', 'Philadelphia', 'Boston'] },
  { name: 'Senegal', confed: 'CAF', tier: 'Elite', group: 'G', hostCities: ['New York', 'Miami', 'Houston'] },
  { name: 'South Africa', confed: 'CAF', tier: 'Strong', group: 'H', hostCities: ['Atlanta', 'Dallas', 'Miami'] },
  { name: 'South Korea', confed: 'AFC', tier: 'Elite', group: 'A', hostCities: ['Los Angeles', 'Seattle', 'San Francisco'] },
  { name: 'Spain', confed: 'UEFA', tier: 'Elite', group: 'B', hostCities: ['Chicago', 'New York', 'Miami'] },
  { name: 'Sweden', confed: 'UEFA', tier: 'Strong', group: 'C', hostCities: ['Seattle', 'Chicago', 'Boston'] },
  { name: 'Switzerland', confed: 'UEFA', tier: 'Elite', group: 'D', hostCities: ['Dallas', 'Atlanta', 'New York'] },
  { name: 'Tunisia', confed: 'CAF', tier: 'Contender', group: 'E', hostCities: ['Houston', 'Miami', 'Atlanta'] },
  { name: 'Turkey', confed: 'UEFA', tier: 'Strong', group: 'F', hostCities: ['New York', 'Boston', 'Philadelphia'] },
  { name: 'Uruguay', confed: 'CONMEBOL', tier: 'Elite', group: 'G', hostCities: ['Miami', 'Houston', 'Los Angeles'] },
  { name: 'USA', confed: 'CONCACAF', tier: 'Elite', group: 'H', hostCities: ['Los Angeles', 'Dallas', 'New York'] },
  { name: 'Uzbekistan', confed: 'AFC', tier: 'Contender', group: 'A', hostCities: ['Seattle', 'Houston', 'Kansas City'] }
];

window.TEAMS_DATA = window.TEAMS_DATA || {};
